# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3794075161867a807fb8f1e046adc02a9343cbed6b8c28e8f2968232f06110e4bacf3d15ec2c6b611142e2876ec9f4c4ecb475db76836bd639b63b7bff5097ae

test:
  secret_key_base: 476ca6822b891c316334ad8acbc0acf698a4d9e31a224b83632defefc460c818b952d9887b9090c6edeafc5dc120c8c4da7c429c6026469beb15d305c84b3c11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
